### ISSUE TITLE
Too much text to process for gpt-3.5-turbo, make it less than 500 words!

### ISSUE THREAD

**Issue by flavienbwk** [lennartle/chadcommit#1]
Hi,

I often get this message : `Too much text to process for gpt-3.5-turbo, make it less than 500 words!` which makes this plugin a bit limited.

According to OpenAI, [1500 words ~= 2048 tokens](https://help.openai.com/en/articles/4936856-what-are-tokens-and-how-to-count-them). [The token limit for gpt-35-turbo is 4096 tokens](https://learn.microsoft.com/en-us/azure/cognitive-services/openai/how-to/chatgpt?pivots=programming-language-chat-completions#managing-conversations).

How can I increase the limit in the plugin ? 

Thank you.

**Comment by lennartle** [comment]
It does not actually count tokens, it's limited by 5000 characters. Sure, I need to change the error message to be more clear, or even remove the limit cap and process the request that will return error if context is to large. It's anyway better to keep commits more atomic.

**Comment by flavienbwk** [comment]
That's a good idea to leave it to the API to return what it handles or not. At the same time, it's future-proof as the API can get new limits in the future.
